pipeline:
  build:
    image: java:openjdk-8
    environment:
          - GRADLE_USER_HOME=~/.gradle
    commands:
      - ./gradlew build

  telegram:
      image: appleboy/drone-telegram
      token: ${TELEGRAM_API_TOKEN}
      to: ${TELEGRAM_NOTIFICATION_USER}