pipeline:
  build:
    image: java:openjdk-8
    environment:
          - GRADLE_USER_HOME=~/.gradle
    commands:
      - ./gradlew build


  telegram:
      image: appleboy/drone-telegram
      secrets: [ telegram_token, telegram_to ]