pipeline:
  build:
    image: java:openjdk-8
    environment:
          - GRADLE_USER_HOME=~/.gradle
    commands:
      - ./gradlew build

    gitter:
        image: plugins/gitter
        webhook: https://webhooks.gitter.im/e/c02743ba74b87b185ce8