language: java

jdk:
     - openjdk8

build:
    ci:
         - ./gradlew build

    post_ci:
         - ls
         - pwd
         - ls ..
         - cp build/test-results/test/*.xml shippable/testresults
