language: java

jdk:
     - openjdk8

build:
    cache: true
    cache_dir_list:
        - /root/.m2

    ci:
        - ls -$HOME
        - ls -la /root/
        - ./gradlew build
        - ./gradlew jacocoTestReport

    post_ci:
        - ./copy-test-results.sh
        - ./copy-coverage.sh

    on_failure:
        - ./gradlew jacocoTestReport
        - ./copy-test-results.sh
        - ./copy-coverage.sh