language: java

jdk:
     - openjdk8

build:
    ci:
         - ./gradlew build
         - ./gradlew jacocoTestReport

    post_ci:
         - cp build/test-results/test/*.xml shippable/testresults
         - mkdir -p shippable/codecoverage/target/site/
         - cp -r build/reports/jacoco shippable/codecoverage/target/site/
