language: java

jdk:
     - openjdk8

build:
    ci:
        - ./gradlew assemble
        - ./gradlew checkstyleMain
        - ./gradlew checkstyleTest
        - ./gradlew test
        - ./gradlew jacocoTestReport

    post_ci:
        - ./ci/copy-test-results.sh
        - ./ci/copy-coverage.sh

    on_failure:
        - ./gradlew jacocoTestReport
        - ./ci/copy-test-results.sh
        - ./ci/copy-coverage.sh

integrations:
    notifications:
      - integrationName: telegram_notification
        type: webhook
        payload:
            - MY_MESSAGE=Successfully triggered web hook
            - BUILD_URL=$BUILD_URL
        on_success: always