language: java

jdk:
     - openjdk8

build:
    ci:
         - ./gradlew build
         - ./gradlew jacocoTestReport

    post_ci:
         - cp build/test-results/test/*.xml shippable/testresults
         - mkdir -p shippable/codecoverage/target/site/jacoco
         - cp build/reports/jacoco/test/jacocoTestReport.xml shippable/codecoverage/target/site/jacoco/jacoco.xml
         - cp -r build/reports/jacoco/test/html shippable/codecoverage/target/site/jacoco/
