language: java

jdk:
     - openjdk8

build:
    ci:
        - ./gradlew build
        - ./gradlew jacocoTestReport

    post_ci:
        - ./copy-test-results.sh
        - ./copy-coverage.sh

    on_failure:
        - ./gradlew jacocoTestReport
        - ./copy-test-results.sh
        - ./copy-coverage.sh