language: java

jdk:
     - openjdk8

build:
    cache: true
    cache_dir_list:
        - $HOME/.gradle/caches
        - $HOME/.gradle/wrapper

    ci:
        - ./gradlew assemble
        - ./gradlew test
        - ./gradlew jacocoTestReport
        - pwd $HOME
        - ls -la $HOME/.android/cache

    post_ci:
        - ./copy-test-results.sh
        - ./copy-coverage.sh

    on_failure:
        - ./gradlew jacocoTestReport
        - ./copy-test-results.sh
        - ./copy-coverage.sh